#-------------------------------------------------
# All PE/Functional-Unit specification goes here
#-------------------------------------------------

#--------------------- Node Attributes and Common Opcode categories -------------------

Attributes:
  - {name: 'immediate', translate: 'const'}
  - {name: 'direct_in', translate: 'input'}
  - {name: 'direct_out', translate: 'output'}
  - {name: 'reflexive', translate: 'acc'}

#OPdef:                                                  # Do not change the name of this key, cgra_context.py searches for it.
#  # Common
#  - {name: 'bridge', type: 'route'}                     # Used to bridge non-bipartite nodes
#  - {name: 'split', type: 'route'}                     # Used to increase node fanout
#  - {name: 'merge', type: 'route'}                     # Used to increase node fanin
#  # PE specific
#  - {name: 'input', type: 'IO'}
#  - {name: 'output', type: 'IO'}
#  - {name: 'add', type: 'alu'}
#  - {name: 'sub', type: 'alu'}
#  - {name: 'mul', type: 'alu'}
#  - {name: 'div', type: 'alu'}
#  - {name: 'fadd', type: 'alu'}
#  - {name: 'fsub', type: 'alu'}
#  - {name: 'fmul', type: 'alu'}
#  - {name: 'fdiv', type: 'alu'}
#  - {name: 'sqrt', type: 'alu'}
#  - {name: 'icmp', type: 'alu'}
#  - {name: 'br', type: 'alu'}
#  - {name: 'phi', type: 'alu'}
#  - {name: 'load', type: 'mem'}                     # Addr in, Data out
#  - {name: 'store', type: 'mem'}                     # Addr in, Data in
#  - {name: 'const', type: 'reg'}
#  - {name: 'acc', type: 'reg'}

Routing:
  - 'bridge'
  - 'split'
  - 'merge'

#--------------------- PE Description -----------------
# Customize by adding opGroups and Ops

PE_int:
  opGroup:
    alu:                                    # Opcodes supported by ALU
      - 'add'
      - 'sub'
      - 'mul'
      - 'div'
      - 'load'
      - 'store'
      - 'icmp'
    reg:
      - 'const'
      - 'acc'
    IO:
      - 'input'
      - 'output'

PE_float:
  opGroup:
    alu:
      - 'fadd'
      - 'fsub'
      - 'fmul'
      - 'fdiv'
      - 'sqrt'
      - 'load'
      - 'store'
    imm:
      - 'const'
    reg:
      - 'acc'
    IO:
      - 'input'
      - 'output'
